package gobject;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GFlagsValue:<br>
 * @value: the flags value<br>
 * @value_name: the name of the value<br>
 * @value_nick: the nickname of the value<br>
 * <br>
 * A structure which contains a single flags value, its name, and its<br>
 * nickname.<br>
 * <i>native declaration : glib-2.0/gobject/genums.h:71</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GObject") 
public class GFlagsValue extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : guint */
	@Field(0) 
	public int value() {
		return this.io.getIntField(this, 0);
	}
	/** C type : guint */
	@Field(0) 
	public GFlagsValue value(int value) {
		this.io.setIntField(this, 0, value);
		return this;
	}
	/** C type : const gchar* */
	@Field(1) 
	public Pointer<Byte > value_name() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : const gchar* */
	@Field(1) 
	public GFlagsValue value_name(Pointer<Byte > value_name) {
		this.io.setPointerField(this, 1, value_name);
		return this;
	}
	/** C type : const gchar* */
	@Field(2) 
	public Pointer<Byte > value_nick() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : const gchar* */
	@Field(2) 
	public GFlagsValue value_nick(Pointer<Byte > value_nick) {
		this.io.setPointerField(this, 2, value_nick);
		return this;
	}
	public GFlagsValue() {
		super();
	}
	public GFlagsValue(Pointer pointer) {
		super(pointer);
	}
}
