package gobject;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GParamSpecFloat:<br>
 * @parent_instance: private #GParamSpec portion<br>
 * @minimum: minimum value for the property specified<br>
 * @maximum: maximum value for the property specified<br>
 * @default_value: default value for the property specified<br>
 * @epsilon: values closer than @epsilon will be considered identical<br>
 *  by g_param_values_cmp(); the default value is 1e-30.<br>
 * <br>
 * A #GParamSpec derived structure that contains the meta data for float properties.<br>
 * <i>native declaration : glib-2.0/gobject/gparamspecs.h:212</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GObject") 
public class GParamSpecFloat extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpec parent_instance() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpecFloat parent_instance(GParamSpec parent_instance) {
		this.io.setNativeObjectField(this, 0, parent_instance);
		return this;
	}
	/** C type : gfloat */
	@Field(1) 
	public float minimum() {
		return this.io.getFloatField(this, 1);
	}
	/** C type : gfloat */
	@Field(1) 
	public GParamSpecFloat minimum(float minimum) {
		this.io.setFloatField(this, 1, minimum);
		return this;
	}
	/** C type : gfloat */
	@Field(2) 
	public float maximum() {
		return this.io.getFloatField(this, 2);
	}
	/** C type : gfloat */
	@Field(2) 
	public GParamSpecFloat maximum(float maximum) {
		this.io.setFloatField(this, 2, maximum);
		return this;
	}
	/** C type : gfloat */
	@Field(3) 
	public float default_value() {
		return this.io.getFloatField(this, 3);
	}
	/** C type : gfloat */
	@Field(3) 
	public GParamSpecFloat default_value(float default_value) {
		this.io.setFloatField(this, 3, default_value);
		return this;
	}
	/** C type : gfloat */
	@Field(4) 
	public float epsilon() {
		return this.io.getFloatField(this, 4);
	}
	/** C type : gfloat */
	@Field(4) 
	public GParamSpecFloat epsilon(float epsilon) {
		this.io.setFloatField(this, 4, epsilon);
		return this;
	}
	public GParamSpecFloat() {
		super();
	}
	public GParamSpecFloat(Pointer pointer) {
		super(pointer);
	}
}
