package gobject;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GParamSpecDouble:<br>
 * @parent_instance: private #GParamSpec portion<br>
 * @minimum: minimum value for the property specified<br>
 * @maximum: maximum value for the property specified<br>
 * @default_value: default value for the property specified<br>
 * @epsilon: values closer than @epsilon will be considered identical<br>
 *  by g_param_values_cmp(); the default value is 1e-90.<br>
 * <br>
 * A #GParamSpec derived structure that contains the meta data for double properties.<br>
 * <i>native declaration : glib-2.0/gobject/gparamspecs.h:230</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GObject") 
public class GParamSpecDouble extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpec parent_instance() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpecDouble parent_instance(GParamSpec parent_instance) {
		this.io.setNativeObjectField(this, 0, parent_instance);
		return this;
	}
	/** C type : gdouble */
	@Field(1) 
	public double minimum() {
		return this.io.getDoubleField(this, 1);
	}
	/** C type : gdouble */
	@Field(1) 
	public GParamSpecDouble minimum(double minimum) {
		this.io.setDoubleField(this, 1, minimum);
		return this;
	}
	/** C type : gdouble */
	@Field(2) 
	public double maximum() {
		return this.io.getDoubleField(this, 2);
	}
	/** C type : gdouble */
	@Field(2) 
	public GParamSpecDouble maximum(double maximum) {
		this.io.setDoubleField(this, 2, maximum);
		return this;
	}
	/** C type : gdouble */
	@Field(3) 
	public double default_value() {
		return this.io.getDoubleField(this, 3);
	}
	/** C type : gdouble */
	@Field(3) 
	public GParamSpecDouble default_value(double default_value) {
		this.io.setDoubleField(this, 3, default_value);
		return this;
	}
	/** C type : gdouble */
	@Field(4) 
	public double epsilon() {
		return this.io.getDoubleField(this, 4);
	}
	/** C type : gdouble */
	@Field(4) 
	public GParamSpecDouble epsilon(double epsilon) {
		this.io.setDoubleField(this, 4, epsilon);
		return this;
	}
	public GParamSpecDouble() {
		super();
	}
	public GParamSpecDouble(Pointer pointer) {
		super(pointer);
	}
}
