package gobject;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GParamSpecChar:<br>
 * @parent_instance: private #GParamSpec portion<br>
 * @minimum: minimum value for the property specified<br>
 * @maximum: maximum value for the property specified<br>
 * @default_value: default value for the property specified<br>
 * <br>
 * A #GParamSpec derived structure that contains the meta data for character properties.<br>
 * <i>native declaration : glib-2.0/gobject/gparamspecs.h:39</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GObject") 
public class GParamSpecChar extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpec parent_instance() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpecChar parent_instance(GParamSpec parent_instance) {
		this.io.setNativeObjectField(this, 0, parent_instance);
		return this;
	}
	/** C type : gint8 */
	@Field(1) 
	public byte minimum() {
		return this.io.getByteField(this, 1);
	}
	/** C type : gint8 */
	@Field(1) 
	public GParamSpecChar minimum(byte minimum) {
		this.io.setByteField(this, 1, minimum);
		return this;
	}
	/** C type : gint8 */
	@Field(2) 
	public byte maximum() {
		return this.io.getByteField(this, 2);
	}
	/** C type : gint8 */
	@Field(2) 
	public GParamSpecChar maximum(byte maximum) {
		this.io.setByteField(this, 2, maximum);
		return this;
	}
	/** C type : gint8 */
	@Field(3) 
	public byte default_value() {
		return this.io.getByteField(this, 3);
	}
	/** C type : gint8 */
	@Field(3) 
	public GParamSpecChar default_value(byte default_value) {
		this.io.setByteField(this, 3, default_value);
		return this;
	}
	public GParamSpecChar() {
		super();
	}
	public GParamSpecChar(Pointer pointer) {
		super(pointer);
	}
}
