package gobject;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GParamSpecEnum:<br>
 * @parent_instance: private #GParamSpec portion<br>
 * @enum_class: the #GEnumClass for the enum<br>
 * @default_value: default value for the property specified<br>
 * <br>
 * A #GParamSpec derived structure that contains the meta data for enum <br>
 * properties.<br>
 * <i>native declaration : glib-2.0/gobject/gparamspecs.h:180</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GObject") 
public class GParamSpecEnum extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpec parent_instance() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : GParamSpec */
	@Field(0) 
	public GParamSpecEnum parent_instance(GParamSpec parent_instance) {
		this.io.setNativeObjectField(this, 0, parent_instance);
		return this;
	}
	/** C type : GEnumClass* */
	@Field(1) 
	public Pointer<GEnumClass > enum_class() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : GEnumClass* */
	@Field(1) 
	public GParamSpecEnum enum_class(Pointer<GEnumClass > enum_class) {
		this.io.setPointerField(this, 1, enum_class);
		return this;
	}
	/** C type : gint */
	@Field(2) 
	public int default_value() {
		return this.io.getIntField(this, 2);
	}
	/** C type : gint */
	@Field(2) 
	public GParamSpecEnum default_value(int default_value) {
		this.io.setIntField(this, 2, default_value);
		return this;
	}
	public GParamSpecEnum() {
		super();
	}
	public GParamSpecEnum(Pointer pointer) {
		super(pointer);
	}
}
