package gobject;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : glib-2.0/gobject/gobject.h:312</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GObject") 
public class GWeakRef extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * <private><br>
	 * C type : priv_union
	 */
	@Field(0) 
	public GWeakRef.priv_union priv() {
		return this.io.getNativeObjectField(this, 0);
	}
	/**
	 * <private><br>
	 * C type : priv_union
	 */
	@Field(0) 
	public GWeakRef priv(GWeakRef.priv_union priv) {
		this.io.setNativeObjectField(this, 0, priv);
		return this;
	}
	/** <i>native declaration : glib-2.0/gobject/gobject.h:311</i> */
	@Union 
	public static class priv_union extends StructObject {
		static {
			BridJ.register();
		}
		/**
		 * Failed to convert value p of type gpointer<br>
		 * C type : gpointer
		 */
		public priv_union() {
			super();
		}
		public priv_union(Pointer pointer) {
			super(pointer);
		}
	};
	public GWeakRef() {
		super();
	}
	public GWeakRef(Pointer pointer) {
		super(pointer);
	}
}
