package gio;
import gio.GIOLibrary.GAsyncInitable;
import gio.GIOLibrary.GAsyncReadyCallback;
import gio.GIOLibrary.GAsyncResult;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * GAsyncInitableIface:<br>
 * @g_iface: The parent interface.<br>
 * @init_async: Starts initialization of the object.<br>
 * @init_finish: Finishes initialization of the object.<br>
 * * Provides an interface for asynchronous initializing object such that<br>
 * initialization may fail.<br>
 * * Since: 2.22<br>
 * <i>native declaration : glib-2.0/gio/gasyncinitable.h:23</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GAsyncInitableIface extends CPPObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GTypeInterface (Unsupported type) */
	/** C type : init_async_callback* */
	@Field(1) 
	public Pointer<GAsyncInitableIface.init_async_callback > init_async() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : init_async_callback* */
	@Field(1) 
	public GAsyncInitableIface init_async(Pointer<GAsyncInitableIface.init_async_callback > init_async) {
		this.io.setPointerField(this, 1, init_async);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/gasyncinitable.h:21</i> */
	public static abstract class init_async_callback extends Callback<init_async_callback > {
		public final void apply(Pointer<GAsyncInitable > initable, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(initable), io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long initable, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/gasyncinitable.h:22</i> */
	public static abstract class gboolean_callback extends Callback<gboolean_callback > {
		public final void apply(Pointer<GAsyncInitable > initable, Pointer<GAsyncResult > res, Pointer<Pointer > error) {
			apply(Pointer.getPeer(initable), Pointer.getPeer(res), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long initable, @Ptr long res, @Ptr long error);
	};
}
