package gio;
import gio.GIOLibrary.GAsyncReadyCallback;
import gio.GIOLibrary.GAsyncResult;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:33</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public class GBufferedInputStreamClass extends CPPObject {
	static {
		BridJ.register();
	}
	/** C type : GFilterInputStreamClass */
	@Field(0) 
	public GFilterInputStreamClass parent_class() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : GFilterInputStreamClass */
	@Field(0) 
	public GBufferedInputStreamClass parent_class(GFilterInputStreamClass parent_class) {
		this.io.setNativeObjectField(this, 0, parent_class);
		return this;
	}
	/**
	 * Async ops: (optional in derived classes)<br>
	 * C type : fill_async_callback*
	 */
	@Field(1) 
	public Pointer<GBufferedInputStreamClass.fill_async_callback > fill_async() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * Async ops: (optional in derived classes)<br>
	 * C type : fill_async_callback*
	 */
	@Field(1) 
	public GBufferedInputStreamClass fill_async(Pointer<GBufferedInputStreamClass.fill_async_callback > fill_async) {
		this.io.setPointerField(this, 1, fill_async);
		return this;
	}
	/** C type : fill_finish_callback* */
	@Field(2) 
	public Pointer<GBufferedInputStreamClass.fill_finish_callback > fill_finish() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : fill_finish_callback* */
	@Field(2) 
	public GBufferedInputStreamClass fill_finish(Pointer<GBufferedInputStreamClass.fill_finish_callback > fill_finish) {
		this.io.setPointerField(this, 2, fill_finish);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(3) 
	public Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(3) 
	public GBufferedInputStreamClass _g_reserved1(Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1) {
		this.io.setPointerField(this, 3, _g_reserved1);
		return this;
	}
	/** C type : _g_reserved2_callback* */
	@Field(4) 
	public Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : _g_reserved2_callback* */
	@Field(4) 
	public GBufferedInputStreamClass _g_reserved2(Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2) {
		this.io.setPointerField(this, 4, _g_reserved2);
		return this;
	}
	/** C type : _g_reserved3_callback* */
	@Field(5) 
	public Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : _g_reserved3_callback* */
	@Field(5) 
	public GBufferedInputStreamClass _g_reserved3(Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3) {
		this.io.setPointerField(this, 5, _g_reserved3);
		return this;
	}
	/** C type : _g_reserved4_callback* */
	@Field(6) 
	public Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : _g_reserved4_callback* */
	@Field(6) 
	public GBufferedInputStreamClass _g_reserved4(Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4) {
		this.io.setPointerField(this, 6, _g_reserved4);
		return this;
	}
	/** C type : _g_reserved5_callback* */
	@Field(7) 
	public Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : _g_reserved5_callback* */
	@Field(7) 
	public GBufferedInputStreamClass _g_reserved5(Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5) {
		this.io.setPointerField(this, 7, _g_reserved5);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:25</i> */
	public static abstract class gssize_callback extends Callback<gssize_callback > {
		public final void apply(Pointer<GBufferedInputStream > stream, @CLong long count, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), count, Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @CLong long count, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:26</i> */
	public static abstract class fill_async_callback extends Callback<fill_async_callback > {
		public final void apply(Pointer<GBufferedInputStream > stream, @CLong long count, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), count, io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, @CLong long count, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:27</i> */
	public static abstract class fill_finish_callback extends Callback<fill_finish_callback > {
		@CLong 
		public final long apply(Pointer<GBufferedInputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			return apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		@CLong 
		public abstract long apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:28</i> */
	public static abstract class _g_reserved1_callback extends Callback<_g_reserved1_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:29</i> */
	public static abstract class _g_reserved2_callback extends Callback<_g_reserved2_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:30</i> */
	public static abstract class _g_reserved3_callback extends Callback<_g_reserved3_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:31</i> */
	public static abstract class _g_reserved4_callback extends Callback<_g_reserved4_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gbufferedinputstream.h:32</i> */
	public static abstract class _g_reserved5_callback extends Callback<_g_reserved5_callback > {
		public abstract void apply();
	};
	public GBufferedInputStreamClass() {
		super();
	}
	public GBufferedInputStreamClass(Pointer pointer) {
		super(pointer);
	}
}
