package gio;
import gio.GIOLibrary.GDBusMethodInvocation;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * GDBusObjectSkeletonClass:<br>
 * @parent_class: The parent class.<br>
 * @authorize_method: Signal class handler for the #GDBusObjectSkeleton::authorize-method signal.<br>
 * * Class structure for #GDBusObjectSkeleton.<br>
 * * Since: 2.30<br>
 * <i>native declaration : glib-2.0/gio/gdbusobjectskeleton.h:31</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GDBusObjectSkeletonClass extends CPPObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/**
	 * < private ><br>
	 * C type : gpointer[8]
	 */
	@Array({8}) 
	@Field(1) 
	public Pointer<gpointer > padding() {
		return this.io.getPointerField(this, 1);
	}
	/** <i>native declaration : glib-2.0/gio/gdbusobjectskeleton.h:30</i> */
	public static abstract class gboolean_callback extends Callback<gboolean_callback > {
		public final void apply(Pointer<GDBusObjectSkeleton > object, Pointer<GDBusInterfaceSkeleton > interface_, Pointer<GDBusMethodInvocation > invocation) {
			apply(Pointer.getPeer(object), Pointer.getPeer(interface_), Pointer.getPeer(invocation));
		}
		public abstract void apply(@Ptr long object, @Ptr long interface_, @Ptr long invocation);
	};
}
