package gio;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GDBusMethodInfo:<br>
 * @ref_count: The reference count or -1 if statically allocated.<br>
 * @name: The name of the D-Bus method, e.g. @RequestName.<br>
 * @in_args: (array zero-terminated=1): A pointer to a %NULL-terminated array of pointers to #GDBusArgInfo structures or %NULL if there are no in arguments.<br>
 * @out_args: (array zero-terminated=1): A pointer to a %NULL-terminated array of pointers to #GDBusArgInfo structures or %NULL if there are no out arguments.<br>
 * @annotations: (array zero-terminated=1): A pointer to a %NULL-terminated array of pointers to #GDBusAnnotationInfo structures or %NULL if there are no annotations.<br>
 * * Information about a method on an D-Bus interface.<br>
 * * Since: 2.26<br>
 * <i>native declaration : glib-2.0/gio/gdbusintrospection.h:50</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public class GDBusMethodInfo extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * < public ><br>
	 * C type : volatile gint
	 */
	@Field(0) 
	public int ref_count() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * < public ><br>
	 * C type : volatile gint
	 */
	@Field(0) 
	public GDBusMethodInfo ref_count(int ref_count) {
		this.io.setIntField(this, 0, ref_count);
		return this;
	}
	/** C type : gchar* */
	@Field(1) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : gchar* */
	@Field(1) 
	public GDBusMethodInfo name(Pointer<Byte > name) {
		this.io.setPointerField(this, 1, name);
		return this;
	}
	/** C type : GDBusArgInfo** */
	@Field(2) 
	public Pointer<Pointer<GDBusArgInfo > > in_args() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : GDBusArgInfo** */
	@Field(2) 
	public GDBusMethodInfo in_args(Pointer<Pointer<GDBusArgInfo > > in_args) {
		this.io.setPointerField(this, 2, in_args);
		return this;
	}
	/** C type : GDBusArgInfo** */
	@Field(3) 
	public Pointer<Pointer<GDBusArgInfo > > out_args() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : GDBusArgInfo** */
	@Field(3) 
	public GDBusMethodInfo out_args(Pointer<Pointer<GDBusArgInfo > > out_args) {
		this.io.setPointerField(this, 3, out_args);
		return this;
	}
	/** C type : GDBusAnnotationInfo** */
	@Field(4) 
	public Pointer<Pointer<GDBusAnnotationInfo > > annotations() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : GDBusAnnotationInfo** */
	@Field(4) 
	public GDBusMethodInfo annotations(Pointer<Pointer<GDBusAnnotationInfo > > annotations) {
		this.io.setPointerField(this, 4, annotations);
		return this;
	}
	public GDBusMethodInfo() {
		super();
	}
	public GDBusMethodInfo(Pointer pointer) {
		super(pointer);
	}
}
