package gio;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Library;
/**
 * GDBusObjectManagerServer:<br>
 * * The #GDBusObjectManagerServer structure contains private data and should<br>
 * only be accessed using the provided API.<br>
 * * Since: 2.30<br>
 * <i>native declaration : glib-2.0/gio/gdbusobjectmanagerserver.h:13</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GDBusObjectManagerServer extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObject (Unsupported type) */
	/** Conversion Error : GDBusObjectManagerServerPrivate* (failed to convert type to Java (undefined type)) */
}
