package gio;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GDBusErrorEntry:<br>
 * @error_code: An error code.<br>
 * @dbus_error_name: The D-Bus error name to associate with @error_code.<br>
 * * Struct used in g_dbus_error_register_error_domain().<br>
 * * Since: 2.26<br>
 * <i>native declaration : glib-2.0/gio/gdbuserror.h:22</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public class GDBusErrorEntry extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : gint */
	@Field(0) 
	public int error_code() {
		return this.io.getIntField(this, 0);
	}
	/** C type : gint */
	@Field(0) 
	public GDBusErrorEntry error_code(int error_code) {
		this.io.setIntField(this, 0, error_code);
		return this;
	}
	/** C type : const gchar* */
	@Field(1) 
	public Pointer<Byte > dbus_error_name() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : const gchar* */
	@Field(1) 
	public GDBusErrorEntry dbus_error_name(Pointer<Byte > dbus_error_name) {
		this.io.setPointerField(this, 1, dbus_error_name);
		return this;
	}
	public GDBusErrorEntry() {
		super();
	}
	public GDBusErrorEntry(Pointer pointer) {
		super(pointer);
	}
}
