package gio;
import gio.GIOLibrary.GVariant;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * GDBusObjectManagerClientClass:<br>
 * @parent_class: The parent class.<br>
 * @interface_proxy_signal: Signal class handler for the #GDBusObjectManagerClient::interface-proxy-signal signal.<br>
 * @interface_proxy_properties_changed: Signal class handler for the #GDBusObjectManagerClient::interface-proxy-properties-changed signal.<br>
 * * Class structure for #GDBusObjectManagerClient.<br>
 * * Since: 2.30<br>
 * <i>native declaration : glib-2.0/gio/gdbusobjectmanagerclient.h:31</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GDBusObjectManagerClientClass extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/**
	 * signals<br>
	 * C type : interface_proxy_signal_callback*
	 */
	@Field(1) 
	public Pointer<GDBusObjectManagerClientClass.interface_proxy_signal_callback > interface_proxy_signal() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * signals<br>
	 * C type : interface_proxy_signal_callback*
	 */
	@Field(1) 
	public GDBusObjectManagerClientClass interface_proxy_signal(Pointer<GDBusObjectManagerClientClass.interface_proxy_signal_callback > interface_proxy_signal) {
		this.io.setPointerField(this, 1, interface_proxy_signal);
		return this;
	}
	/** C type : interface_proxy_properties_changed_callback* */
	@Field(2) 
	public Pointer<GDBusObjectManagerClientClass.interface_proxy_properties_changed_callback > interface_proxy_properties_changed() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : interface_proxy_properties_changed_callback* */
	@Field(2) 
	public GDBusObjectManagerClientClass interface_proxy_properties_changed(Pointer<GDBusObjectManagerClientClass.interface_proxy_properties_changed_callback > interface_proxy_properties_changed) {
		this.io.setPointerField(this, 2, interface_proxy_properties_changed);
		return this;
	}
	/**
	 * < private ><br>
	 * C type : gpointer[8]
	 */
	@Array({8}) 
	@Field(3) 
	public Pointer<gpointer > padding() {
		return this.io.getPointerField(this, 3);
	}
	/** <i>native declaration : glib-2.0/gio/gdbusobjectmanagerclient.h:29</i> */
	public static abstract class interface_proxy_signal_callback extends Callback<interface_proxy_signal_callback > {
		public final void apply(Pointer<GDBusObjectManagerClient > manager, Pointer<GDBusObjectProxy > object_proxy, Pointer<GDBusProxy > interface_proxy, Pointer<Byte > sender_name, Pointer<Byte > signal_name, Pointer<GVariant > parameters) {
			apply(Pointer.getPeer(manager), Pointer.getPeer(object_proxy), Pointer.getPeer(interface_proxy), Pointer.getPeer(sender_name), Pointer.getPeer(signal_name), Pointer.getPeer(parameters));
		}
		public abstract void apply(@Ptr long manager, @Ptr long object_proxy, @Ptr long interface_proxy, @Ptr long sender_name, @Ptr long signal_name, @Ptr long parameters);
	};
	/** <i>native declaration : glib-2.0/gio/gdbusobjectmanagerclient.h:30</i> */
	public static abstract class interface_proxy_properties_changed_callback extends Callback<interface_proxy_properties_changed_callback > {
		public final void apply(Pointer<GDBusObjectManagerClient > manager, Pointer<GDBusObjectProxy > object_proxy, Pointer<GDBusProxy > interface_proxy, Pointer<GVariant > changed_properties, Pointer<Pointer<Byte > > invalidated_properties) {
			apply(Pointer.getPeer(manager), Pointer.getPeer(object_proxy), Pointer.getPeer(interface_proxy), Pointer.getPeer(changed_properties), Pointer.getPeer(invalidated_properties));
		}
		public abstract void apply(@Ptr long manager, @Ptr long object_proxy, @Ptr long interface_proxy, @Ptr long changed_properties, @Ptr long invalidated_properties);
	};
}
