package gio;
import gio.GIOLibrary.GVariant;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * GDBusProxyClass:<br>
 * @g_properties_changed: Signal class handler for the #GDBusProxy::g-properties-changed signal.<br>
 * @g_signal: Signal class handler for the #GDBusProxy::g-signal signal.<br>
 * * Class structure for #GDBusProxy.<br>
 * * Since: 2.26<br>
 * <i>native declaration : glib-2.0/gio/gdbusproxy.h:31</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GDBusProxyClass extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/**
	 * Signals<br>
	 * C type : g_properties_changed_callback*
	 */
	@Field(1) 
	public Pointer<GDBusProxyClass.g_properties_changed_callback > g_properties_changed() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * Signals<br>
	 * C type : g_properties_changed_callback*
	 */
	@Field(1) 
	public GDBusProxyClass g_properties_changed(Pointer<GDBusProxyClass.g_properties_changed_callback > g_properties_changed) {
		this.io.setPointerField(this, 1, g_properties_changed);
		return this;
	}
	/** C type : g_signal_callback* */
	@Field(2) 
	public Pointer<GDBusProxyClass.g_signal_callback > g_signal() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : g_signal_callback* */
	@Field(2) 
	public GDBusProxyClass g_signal(Pointer<GDBusProxyClass.g_signal_callback > g_signal) {
		this.io.setPointerField(this, 2, g_signal);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : gpointer[32]
	 */
	@Array({32}) 
	@Field(3) 
	public Pointer<gpointer > padding() {
		return this.io.getPointerField(this, 3);
	}
	/** <i>native declaration : glib-2.0/gio/gdbusproxy.h:29</i> */
	public static abstract class g_properties_changed_callback extends Callback<g_properties_changed_callback > {
		public final void apply(Pointer<GDBusProxy > proxy, Pointer<GVariant > changed_properties, Pointer<Pointer<Byte > > invalidated_properties) {
			apply(Pointer.getPeer(proxy), Pointer.getPeer(changed_properties), Pointer.getPeer(invalidated_properties));
		}
		public abstract void apply(@Ptr long proxy, @Ptr long changed_properties, @Ptr long invalidated_properties);
	};
	/** <i>native declaration : glib-2.0/gio/gdbusproxy.h:30</i> */
	public static abstract class g_signal_callback extends Callback<g_signal_callback > {
		public final void apply(Pointer<GDBusProxy > proxy, Pointer<Byte > sender_name, Pointer<Byte > signal_name, Pointer<GVariant > parameters) {
			apply(Pointer.getPeer(proxy), Pointer.getPeer(sender_name), Pointer.getPeer(signal_name), Pointer.getPeer(parameters));
		}
		public abstract void apply(@Ptr long proxy, @Ptr long sender_name, @Ptr long signal_name, @Ptr long parameters);
	};
}
