package gio;
import gio.GIOLibrary.GDBusPropertyInfoFlags;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GDBusPropertyInfo:<br>
 * @ref_count: The reference count or -1 if statically allocated.<br>
 * @name: The name of the D-Bus property, e.g. "SupportedFilesystems".<br>
 * @signature: The D-Bus signature of the property (a single complete type).<br>
 * @flags: Access control flags for the property.<br>
 * @annotations: (array zero-terminated=1): A pointer to a %NULL-terminated array of pointers to #GDBusAnnotationInfo structures or %NULL if there are no annotations.<br>
 * * Information about a D-Bus property on a D-Bus interface.<br>
 * * Since: 2.26<br>
 * <i>native declaration : glib-2.0/gio/gdbusintrospection.h:84</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public class GDBusPropertyInfo extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * < public ><br>
	 * C type : volatile gint
	 */
	@Field(0) 
	public int ref_count() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * < public ><br>
	 * C type : volatile gint
	 */
	@Field(0) 
	public GDBusPropertyInfo ref_count(int ref_count) {
		this.io.setIntField(this, 0, ref_count);
		return this;
	}
	/** C type : gchar* */
	@Field(1) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : gchar* */
	@Field(1) 
	public GDBusPropertyInfo name(Pointer<Byte > name) {
		this.io.setPointerField(this, 1, name);
		return this;
	}
	/** C type : gchar* */
	@Field(2) 
	public Pointer<Byte > signature() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : gchar* */
	@Field(2) 
	public GDBusPropertyInfo signature(Pointer<Byte > signature) {
		this.io.setPointerField(this, 2, signature);
		return this;
	}
	/** C type : GDBusPropertyInfoFlags */
	@Field(3) 
	public IntValuedEnum<GDBusPropertyInfoFlags > flags() {
		return this.io.getEnumField(this, 3);
	}
	/** C type : GDBusPropertyInfoFlags */
	@Field(3) 
	public GDBusPropertyInfo flags(IntValuedEnum<GDBusPropertyInfoFlags > flags) {
		this.io.setEnumField(this, 3, flags);
		return this;
	}
	/** C type : GDBusAnnotationInfo** */
	@Field(4) 
	public Pointer<Pointer<GDBusAnnotationInfo > > annotations() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : GDBusAnnotationInfo** */
	@Field(4) 
	public GDBusPropertyInfo annotations(Pointer<Pointer<GDBusAnnotationInfo > > annotations) {
		this.io.setPointerField(this, 4, annotations);
		return this;
	}
	public GDBusPropertyInfo() {
		super();
	}
	public GDBusPropertyInfo(Pointer pointer) {
		super(pointer);
	}
}
