package gio;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/gio/gfilteroutputstream.h:20</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public class GFilterOutputStreamClass extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : GOutputStreamClass */
	@Field(0) 
	public GOutputStreamClass parent_class() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : GOutputStreamClass */
	@Field(0) 
	public GFilterOutputStreamClass parent_class(GOutputStreamClass parent_class) {
		this.io.setNativeObjectField(this, 0, parent_class);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(1) 
	public Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(1) 
	public GFilterOutputStreamClass _g_reserved1(Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1) {
		this.io.setPointerField(this, 1, _g_reserved1);
		return this;
	}
	/** C type : _g_reserved2_callback* */
	@Field(2) 
	public Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : _g_reserved2_callback* */
	@Field(2) 
	public GFilterOutputStreamClass _g_reserved2(Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2) {
		this.io.setPointerField(this, 2, _g_reserved2);
		return this;
	}
	/** C type : _g_reserved3_callback* */
	@Field(3) 
	public Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : _g_reserved3_callback* */
	@Field(3) 
	public GFilterOutputStreamClass _g_reserved3(Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3) {
		this.io.setPointerField(this, 3, _g_reserved3);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/gfilteroutputstream.h:17</i> */
	public static abstract class _g_reserved1_callback extends Callback<_g_reserved1_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gfilteroutputstream.h:18</i> */
	public static abstract class _g_reserved2_callback extends Callback<_g_reserved2_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gfilteroutputstream.h:19</i> */
	public static abstract class _g_reserved3_callback extends Callback<_g_reserved3_callback > {
		public abstract void apply();
	};
	public GFilterOutputStreamClass() {
		super();
	}
	public GFilterOutputStreamClass(Pointer pointer) {
		super(pointer);
	}
}
