package gio;
import gio.GIOLibrary.GFile;
import gio.GIOLibrary.GFileMonitorEvent;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : glib-2.0/gio/gfilemonitor.h:34</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GFileMonitorClass extends CPPObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/**
	 * Signals<br>
	 * C type : changed_callback*
	 */
	@Field(1) 
	public Pointer<gio.GVolumeIface.changed_callback > changed() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * Signals<br>
	 * C type : changed_callback*
	 */
	@Field(1) 
	public GFileMonitorClass changed(Pointer<gio.GVolumeIface.changed_callback > changed) {
		this.io.setPointerField(this, 1, changed);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(2) 
	public Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(2) 
	public GFileMonitorClass _g_reserved1(Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1) {
		this.io.setPointerField(this, 2, _g_reserved1);
		return this;
	}
	/** C type : _g_reserved2_callback* */
	@Field(3) 
	public Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : _g_reserved2_callback* */
	@Field(3) 
	public GFileMonitorClass _g_reserved2(Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2) {
		this.io.setPointerField(this, 3, _g_reserved2);
		return this;
	}
	/** C type : _g_reserved3_callback* */
	@Field(4) 
	public Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : _g_reserved3_callback* */
	@Field(4) 
	public GFileMonitorClass _g_reserved3(Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3) {
		this.io.setPointerField(this, 4, _g_reserved3);
		return this;
	}
	/** C type : _g_reserved4_callback* */
	@Field(5) 
	public Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : _g_reserved4_callback* */
	@Field(5) 
	public GFileMonitorClass _g_reserved4(Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4) {
		this.io.setPointerField(this, 5, _g_reserved4);
		return this;
	}
	/** C type : _g_reserved5_callback* */
	@Field(6) 
	public Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : _g_reserved5_callback* */
	@Field(6) 
	public GFileMonitorClass _g_reserved5(Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5) {
		this.io.setPointerField(this, 6, _g_reserved5);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/gfilemonitor.h:27</i> */
	public static abstract class changed_callback extends Callback<changed_callback > {
		public final void apply(Pointer<GFileMonitor > monitor, Pointer<GFile > file, Pointer<GFile > other_file, IntValuedEnum<GFileMonitorEvent > event_type) {
			apply(Pointer.getPeer(monitor), Pointer.getPeer(file), Pointer.getPeer(other_file), (int)event_type.value());
		}
		public abstract void apply(@Ptr long monitor, @Ptr long file, @Ptr long other_file, int event_type);
	};
	/** <i>native declaration : glib-2.0/gio/gfilemonitor.h:28</i> */
	public static abstract class gboolean_callback extends Callback<gboolean_callback > {
		public final void apply(Pointer<GFileMonitor > monitor) {
			apply(Pointer.getPeer(monitor));
		}
		public abstract void apply(@Ptr long monitor);
	};
	/** <i>native declaration : glib-2.0/gio/gfilemonitor.h:29</i> */
	public static abstract class _g_reserved1_callback extends Callback<_g_reserved1_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gfilemonitor.h:30</i> */
	public static abstract class _g_reserved2_callback extends Callback<_g_reserved2_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gfilemonitor.h:31</i> */
	public static abstract class _g_reserved3_callback extends Callback<_g_reserved3_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gfilemonitor.h:32</i> */
	public static abstract class _g_reserved4_callback extends Callback<_g_reserved4_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gfilemonitor.h:33</i> */
	public static abstract class _g_reserved5_callback extends Callback<_g_reserved5_callback > {
		public abstract void apply();
	};
}
