package gio;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/gio/gfilteroutputstream.h:10</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public class GFilterOutputStream extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : GOutputStream */
	@Field(0) 
	public GOutputStream parent_instance() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : GOutputStream */
	@Field(0) 
	public GFilterOutputStream parent_instance(GOutputStream parent_instance) {
		this.io.setNativeObjectField(this, 0, parent_instance);
		return this;
	}
	/**
	 * < protected ><br>
	 * C type : GOutputStream*
	 */
	@Field(1) 
	public Pointer<GOutputStream > base_stream() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * < protected ><br>
	 * C type : GOutputStream*
	 */
	@Field(1) 
	public GFilterOutputStream base_stream(Pointer<GOutputStream > base_stream) {
		this.io.setPointerField(this, 1, base_stream);
		return this;
	}
	public GFilterOutputStream() {
		super();
	}
	public GFilterOutputStream(Pointer pointer) {
		super(pointer);
	}
}
