package gio;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : glib-2.0/gio/ginetaddress.h:14</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GInetAddressClass extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/** C type : to_string_callback* */
	@Field(1) 
	public Pointer<GInetAddressClass.to_string_callback > to_string() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : to_string_callback* */
	@Field(1) 
	public GInetAddressClass to_string(Pointer<GInetAddressClass.to_string_callback > to_string) {
		this.io.setPointerField(this, 1, to_string);
		return this;
	}
	/** C type : to_bytes_callback* */
	@Field(2) 
	public Pointer<GInetAddressClass.to_bytes_callback > to_bytes() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : to_bytes_callback* */
	@Field(2) 
	public GInetAddressClass to_bytes(Pointer<GInetAddressClass.to_bytes_callback > to_bytes) {
		this.io.setPointerField(this, 2, to_bytes);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/ginetaddress.h:12</i> */
	public static abstract class to_string_callback extends Callback<to_string_callback > {
		public final Pointer<Byte > apply(Pointer<GInetAddress > address) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(address)), Byte.class);
		}
		@Ptr 
		public abstract long apply(@Ptr long address);
	};
	/** <i>native declaration : glib-2.0/gio/ginetaddress.h:13</i> */
	public static abstract class to_bytes_callback extends Callback<to_bytes_callback > {
		public final Pointer<Byte > apply(Pointer<GInetAddress > address) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(address)), Byte.class);
		}
		@Ptr 
		public abstract long apply(@Ptr long address);
	};
}
