package gio;
import gio.GIOLibrary.GAsyncReadyCallback;
import gio.GIOLibrary.GAsyncResult;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : glib-2.0/gio/ginputstream.h:50</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GInputStreamClass extends CPPObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/**
	 * Async ops: (optional in derived classes)<br>
	 * C type : read_async_callback*
	 */
	@Field(1) 
	public Pointer<GInputStreamClass.read_async_callback > read_async() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * Async ops: (optional in derived classes)<br>
	 * C type : read_async_callback*
	 */
	@Field(1) 
	public GInputStreamClass read_async(Pointer<GInputStreamClass.read_async_callback > read_async) {
		this.io.setPointerField(this, 1, read_async);
		return this;
	}
	/** C type : skip_async_callback* */
	@Field(2) 
	public Pointer<GInputStreamClass.skip_async_callback > skip_async() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : skip_async_callback* */
	@Field(2) 
	public GInputStreamClass skip_async(Pointer<GInputStreamClass.skip_async_callback > skip_async) {
		this.io.setPointerField(this, 2, skip_async);
		return this;
	}
	/** C type : close_async_callback* */
	@Field(3) 
	public Pointer<gio.GIOStreamClass.close_async_callback > close_async() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : close_async_callback* */
	@Field(3) 
	public GInputStreamClass close_async(Pointer<gio.GIOStreamClass.close_async_callback > close_async) {
		this.io.setPointerField(this, 3, close_async);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(4) 
	public Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(4) 
	public GInputStreamClass _g_reserved1(Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1) {
		this.io.setPointerField(this, 4, _g_reserved1);
		return this;
	}
	/** C type : _g_reserved2_callback* */
	@Field(5) 
	public Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : _g_reserved2_callback* */
	@Field(5) 
	public GInputStreamClass _g_reserved2(Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2) {
		this.io.setPointerField(this, 5, _g_reserved2);
		return this;
	}
	/** C type : _g_reserved3_callback* */
	@Field(6) 
	public Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : _g_reserved3_callback* */
	@Field(6) 
	public GInputStreamClass _g_reserved3(Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3) {
		this.io.setPointerField(this, 6, _g_reserved3);
		return this;
	}
	/** C type : _g_reserved4_callback* */
	@Field(7) 
	public Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : _g_reserved4_callback* */
	@Field(7) 
	public GInputStreamClass _g_reserved4(Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4) {
		this.io.setPointerField(this, 7, _g_reserved4);
		return this;
	}
	/** C type : _g_reserved5_callback* */
	@Field(8) 
	public Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : _g_reserved5_callback* */
	@Field(8) 
	public GInputStreamClass _g_reserved5(Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5) {
		this.io.setPointerField(this, 8, _g_reserved5);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:36</i> */
	public static abstract class gssize_callback extends Callback<gssize_callback > {
		public final void apply(Pointer<GInputStream > stream, Pointer<? > buffer, @CLong long count, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(buffer), count, Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long buffer, @CLong long count, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:37</i> */
	public static abstract class gssize_callback2 extends Callback<gssize_callback2 > {
		public final void apply(Pointer<GInputStream > stream, @CLong long count, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), count, Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @CLong long count, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:38</i> */
	public static abstract class gboolean_callback extends Callback<gboolean_callback > {
		public final void apply(Pointer<GInputStream > stream, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:39</i> */
	public static abstract class read_async_callback extends Callback<read_async_callback > {
		public final void apply(Pointer<GInputStream > stream, Pointer<? > buffer, @CLong long count, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(buffer), count, io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, @Ptr long buffer, @CLong long count, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:40</i> */
	public static abstract class gssize_callback3 extends Callback<gssize_callback3 > {
		public final void apply(Pointer<GInputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:41</i> */
	public static abstract class skip_async_callback extends Callback<skip_async_callback > {
		public final void apply(Pointer<GInputStream > stream, @CLong long count, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), count, io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, @CLong long count, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:42</i> */
	public static abstract class gssize_callback4 extends Callback<gssize_callback4 > {
		public final void apply(Pointer<GInputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:43</i> */
	public static abstract class close_async_callback extends Callback<close_async_callback > {
		public final void apply(Pointer<GInputStream > stream, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:44</i> */
	public static abstract class gboolean_callback2 extends Callback<gboolean_callback2 > {
		public final void apply(Pointer<GInputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:45</i> */
	public static abstract class _g_reserved1_callback extends Callback<_g_reserved1_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:46</i> */
	public static abstract class _g_reserved2_callback extends Callback<_g_reserved2_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:47</i> */
	public static abstract class _g_reserved3_callback extends Callback<_g_reserved3_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:48</i> */
	public static abstract class _g_reserved4_callback extends Callback<_g_reserved4_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/ginputstream.h:49</i> */
	public static abstract class _g_reserved5_callback extends Callback<_g_reserved5_callback > {
		public abstract void apply();
	};
}
