package gio;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/gio/giotypes.h:290</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public class GInputVector extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * Failed to convert value buffer of type gpointer<br>
	 * C type : gpointer
	 */
	/** C type : gsize */
	@CLong 
	@Field(1) 
	public long size() {
		return this.io.getCLongField(this, 1);
	}
	/** C type : gsize */
	@CLong 
	@Field(1) 
	public GInputVector size(long size) {
		this.io.setCLongField(this, 1, size);
		return this;
	}
	public GInputVector() {
		super();
	}
	public GInputVector(Pointer pointer) {
		super(pointer);
	}
}
