package gio;
import gio.GIOLibrary.GVariant;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : glib-2.0/gio/gmenumodel.h:67</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GMenuAttributeIterClass extends CPPObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/** <i>native declaration : glib-2.0/gio/gmenumodel.h:66</i> */
	public static abstract class gboolean_callback extends Callback<gboolean_callback > {
		public final void apply(Pointer<GMenuAttributeIter > iter, Pointer<Pointer<Byte > > out_name, Pointer<Pointer<GVariant > > value) {
			apply(Pointer.getPeer(iter), Pointer.getPeer(out_name), Pointer.getPeer(value));
		}
		public abstract void apply(@Ptr long iter, @Ptr long out_name, @Ptr long value);
	};
}
