package gio;
import gio.GIOLibrary.GAskPasswordFlags;
import gio.GIOLibrary.GMountOperationResult;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : glib-2.0/gio/gmountoperation.h:45</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GMountOperationClass extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/** C type : ask_password_callback* */
	@Field(1) 
	public Pointer<GMountOperationClass.ask_password_callback > ask_password() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : ask_password_callback* */
	@Field(1) 
	public GMountOperationClass ask_password(Pointer<GMountOperationClass.ask_password_callback > ask_password) {
		this.io.setPointerField(this, 1, ask_password);
		return this;
	}
	/** C type : ask_question_callback* */
	@Field(2) 
	public Pointer<GMountOperationClass.ask_question_callback > ask_question() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : ask_question_callback* */
	@Field(2) 
	public GMountOperationClass ask_question(Pointer<GMountOperationClass.ask_question_callback > ask_question) {
		this.io.setPointerField(this, 2, ask_question);
		return this;
	}
	/** C type : reply_callback* */
	@Field(3) 
	public Pointer<GMountOperationClass.reply_callback > reply() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : reply_callback* */
	@Field(3) 
	public GMountOperationClass reply(Pointer<GMountOperationClass.reply_callback > reply) {
		this.io.setPointerField(this, 3, reply);
		return this;
	}
	/** C type : aborted_callback* */
	@Field(4) 
	public Pointer<GMountOperationClass.aborted_callback > aborted() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : aborted_callback* */
	@Field(4) 
	public GMountOperationClass aborted(Pointer<GMountOperationClass.aborted_callback > aborted) {
		this.io.setPointerField(this, 4, aborted);
		return this;
	}
	/** C type : show_processes_callback* */
	@Field(5) 
	public Pointer<GMountOperationClass.show_processes_callback > show_processes() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : show_processes_callback* */
	@Field(5) 
	public GMountOperationClass show_processes(Pointer<GMountOperationClass.show_processes_callback > show_processes) {
		this.io.setPointerField(this, 5, show_processes);
		return this;
	}
	/** C type : show_unmount_progress_callback* */
	@Field(6) 
	public Pointer<GMountOperationClass.show_unmount_progress_callback > show_unmount_progress() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : show_unmount_progress_callback* */
	@Field(6) 
	public GMountOperationClass show_unmount_progress(Pointer<GMountOperationClass.show_unmount_progress_callback > show_unmount_progress) {
		this.io.setPointerField(this, 6, show_unmount_progress);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(7) 
	public Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(7) 
	public GMountOperationClass _g_reserved1(Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1) {
		this.io.setPointerField(this, 7, _g_reserved1);
		return this;
	}
	/** C type : _g_reserved2_callback* */
	@Field(8) 
	public Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : _g_reserved2_callback* */
	@Field(8) 
	public GMountOperationClass _g_reserved2(Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2) {
		this.io.setPointerField(this, 8, _g_reserved2);
		return this;
	}
	/** C type : _g_reserved3_callback* */
	@Field(9) 
	public Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : _g_reserved3_callback* */
	@Field(9) 
	public GMountOperationClass _g_reserved3(Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3) {
		this.io.setPointerField(this, 9, _g_reserved3);
		return this;
	}
	/** C type : _g_reserved4_callback* */
	@Field(10) 
	public Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : _g_reserved4_callback* */
	@Field(10) 
	public GMountOperationClass _g_reserved4(Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4) {
		this.io.setPointerField(this, 10, _g_reserved4);
		return this;
	}
	/** C type : _g_reserved5_callback* */
	@Field(11) 
	public Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : _g_reserved5_callback* */
	@Field(11) 
	public GMountOperationClass _g_reserved5(Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5) {
		this.io.setPointerField(this, 11, _g_reserved5);
		return this;
	}
	/** C type : _g_reserved6_callback* */
	@Field(12) 
	public Pointer<gio.GVfsClass._g_reserved6_callback > _g_reserved6() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : _g_reserved6_callback* */
	@Field(12) 
	public GMountOperationClass _g_reserved6(Pointer<gio.GVfsClass._g_reserved6_callback > _g_reserved6) {
		this.io.setPointerField(this, 12, _g_reserved6);
		return this;
	}
	/** C type : _g_reserved7_callback* */
	@Field(13) 
	public Pointer<gio.GSocketClass._g_reserved7_callback > _g_reserved7() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : _g_reserved7_callback* */
	@Field(13) 
	public GMountOperationClass _g_reserved7(Pointer<gio.GSocketClass._g_reserved7_callback > _g_reserved7) {
		this.io.setPointerField(this, 13, _g_reserved7);
		return this;
	}
	/** C type : _g_reserved8_callback* */
	@Field(14) 
	public Pointer<gio.GSocketClass._g_reserved8_callback > _g_reserved8() {
		return this.io.getPointerField(this, 14);
	}
	/** C type : _g_reserved8_callback* */
	@Field(14) 
	public GMountOperationClass _g_reserved8(Pointer<gio.GSocketClass._g_reserved8_callback > _g_reserved8) {
		this.io.setPointerField(this, 14, _g_reserved8);
		return this;
	}
	/** C type : _g_reserved9_callback* */
	@Field(15) 
	public Pointer<gio.GSocketClass._g_reserved9_callback > _g_reserved9() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : _g_reserved9_callback* */
	@Field(15) 
	public GMountOperationClass _g_reserved9(Pointer<gio.GSocketClass._g_reserved9_callback > _g_reserved9) {
		this.io.setPointerField(this, 15, _g_reserved9);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:30</i> */
	public static abstract class ask_password_callback extends Callback<ask_password_callback > {
		public final void apply(Pointer<GMountOperation > op, Pointer<Byte > message, Pointer<Byte > default_user, Pointer<Byte > default_domain, IntValuedEnum<GAskPasswordFlags > flags) {
			apply(Pointer.getPeer(op), Pointer.getPeer(message), Pointer.getPeer(default_user), Pointer.getPeer(default_domain), (int)flags.value());
		}
		public abstract void apply(@Ptr long op, @Ptr long message, @Ptr long default_user, @Ptr long default_domain, int flags);
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:31</i> */
	public static abstract class ask_question_callback extends Callback<ask_question_callback > {
		public final void apply(Pointer<GMountOperation > op, Pointer<Byte > message, Pointer<Pointer<Byte > > choices) {
			apply(Pointer.getPeer(op), Pointer.getPeer(message), Pointer.getPeer(choices));
		}
		public abstract void apply(@Ptr long op, @Ptr long message, @Ptr long choices);
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:32</i> */
	public static abstract class reply_callback extends Callback<reply_callback > {
		public final void apply(Pointer<GMountOperation > op, IntValuedEnum<GMountOperationResult > result) {
			apply(Pointer.getPeer(op), (int)result.value());
		}
		public abstract void apply(@Ptr long op, int result);
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:33</i> */
	public static abstract class aborted_callback extends Callback<aborted_callback > {
		public final void apply(Pointer<GMountOperation > op) {
			apply(Pointer.getPeer(op));
		}
		public abstract void apply(@Ptr long op);
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:34</i> */
	public static abstract class show_processes_callback extends Callback<show_processes_callback > {
		public final void apply(Pointer<GMountOperation > op, Pointer<Byte > message, Pointer processes, Pointer<Pointer<Byte > > choices) {
			apply(Pointer.getPeer(op), Pointer.getPeer(message), Pointer.getPeer(processes), Pointer.getPeer(choices));
		}
		public abstract void apply(@Ptr long op, @Ptr long message, @Ptr long processes, @Ptr long choices);
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:35</i> */
	public static abstract class show_unmount_progress_callback extends Callback<show_unmount_progress_callback > {
		public final void apply(Pointer<GMountOperation > op, Pointer<Byte > message, long time_left, long bytes_left) {
			apply(Pointer.getPeer(op), Pointer.getPeer(message), time_left, bytes_left);
		}
		public abstract void apply(@Ptr long op, @Ptr long message, long time_left, long bytes_left);
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:36</i> */
	public static abstract class _g_reserved1_callback extends Callback<_g_reserved1_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:37</i> */
	public static abstract class _g_reserved2_callback extends Callback<_g_reserved2_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:38</i> */
	public static abstract class _g_reserved3_callback extends Callback<_g_reserved3_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:39</i> */
	public static abstract class _g_reserved4_callback extends Callback<_g_reserved4_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:40</i> */
	public static abstract class _g_reserved5_callback extends Callback<_g_reserved5_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:41</i> */
	public static abstract class _g_reserved6_callback extends Callback<_g_reserved6_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:42</i> */
	public static abstract class _g_reserved7_callback extends Callback<_g_reserved7_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:43</i> */
	public static abstract class _g_reserved8_callback extends Callback<_g_reserved8_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gmountoperation.h:44</i> */
	public static abstract class _g_reserved9_callback extends Callback<_g_reserved9_callback > {
		public abstract void apply();
	};
}
