package gio;
import gio.GIOLibrary.GAsyncReadyCallback;
import gio.GIOLibrary.GAsyncResult;
import gio.GIOLibrary.GOutputStreamSpliceFlags;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : glib-2.0/gio/goutputstream.h:66</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GOutputStreamClass extends CPPObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/** C type : write_async_callback* */
	@Field(1) 
	public Pointer<GOutputStreamClass.write_async_callback > write_async() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : write_async_callback* */
	@Field(1) 
	public GOutputStreamClass write_async(Pointer<GOutputStreamClass.write_async_callback > write_async) {
		this.io.setPointerField(this, 1, write_async);
		return this;
	}
	/** C type : splice_async_callback* */
	@Field(2) 
	public Pointer<GOutputStreamClass.splice_async_callback > splice_async() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : splice_async_callback* */
	@Field(2) 
	public GOutputStreamClass splice_async(Pointer<GOutputStreamClass.splice_async_callback > splice_async) {
		this.io.setPointerField(this, 2, splice_async);
		return this;
	}
	/** C type : flush_async_callback* */
	@Field(3) 
	public Pointer<GOutputStreamClass.flush_async_callback > flush_async() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : flush_async_callback* */
	@Field(3) 
	public GOutputStreamClass flush_async(Pointer<GOutputStreamClass.flush_async_callback > flush_async) {
		this.io.setPointerField(this, 3, flush_async);
		return this;
	}
	/** C type : close_async_callback* */
	@Field(4) 
	public Pointer<gio.GIOStreamClass.close_async_callback > close_async() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : close_async_callback* */
	@Field(4) 
	public GOutputStreamClass close_async(Pointer<gio.GIOStreamClass.close_async_callback > close_async) {
		this.io.setPointerField(this, 4, close_async);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(5) 
	public Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(5) 
	public GOutputStreamClass _g_reserved1(Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1) {
		this.io.setPointerField(this, 5, _g_reserved1);
		return this;
	}
	/** C type : _g_reserved2_callback* */
	@Field(6) 
	public Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : _g_reserved2_callback* */
	@Field(6) 
	public GOutputStreamClass _g_reserved2(Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2) {
		this.io.setPointerField(this, 6, _g_reserved2);
		return this;
	}
	/** C type : _g_reserved3_callback* */
	@Field(7) 
	public Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : _g_reserved3_callback* */
	@Field(7) 
	public GOutputStreamClass _g_reserved3(Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3) {
		this.io.setPointerField(this, 7, _g_reserved3);
		return this;
	}
	/** C type : _g_reserved4_callback* */
	@Field(8) 
	public Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : _g_reserved4_callback* */
	@Field(8) 
	public GOutputStreamClass _g_reserved4(Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4) {
		this.io.setPointerField(this, 8, _g_reserved4);
		return this;
	}
	/** C type : _g_reserved5_callback* */
	@Field(9) 
	public Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : _g_reserved5_callback* */
	@Field(9) 
	public GOutputStreamClass _g_reserved5(Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5) {
		this.io.setPointerField(this, 9, _g_reserved5);
		return this;
	}
	/** C type : _g_reserved6_callback* */
	@Field(10) 
	public Pointer<gio.GVfsClass._g_reserved6_callback > _g_reserved6() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : _g_reserved6_callback* */
	@Field(10) 
	public GOutputStreamClass _g_reserved6(Pointer<gio.GVfsClass._g_reserved6_callback > _g_reserved6) {
		this.io.setPointerField(this, 10, _g_reserved6);
		return this;
	}
	/** C type : _g_reserved7_callback* */
	@Field(11) 
	public Pointer<gio.GSocketClass._g_reserved7_callback > _g_reserved7() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : _g_reserved7_callback* */
	@Field(11) 
	public GOutputStreamClass _g_reserved7(Pointer<gio.GSocketClass._g_reserved7_callback > _g_reserved7) {
		this.io.setPointerField(this, 11, _g_reserved7);
		return this;
	}
	/** C type : _g_reserved8_callback* */
	@Field(12) 
	public Pointer<gio.GSocketClass._g_reserved8_callback > _g_reserved8() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : _g_reserved8_callback* */
	@Field(12) 
	public GOutputStreamClass _g_reserved8(Pointer<gio.GSocketClass._g_reserved8_callback > _g_reserved8) {
		this.io.setPointerField(this, 12, _g_reserved8);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:46</i> */
	public static abstract class gssize_callback extends Callback<gssize_callback > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<? > buffer, @CLong long count, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(buffer), count, Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long buffer, @CLong long count, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:47</i> */
	public static abstract class gssize_callback2 extends Callback<gssize_callback2 > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GInputStream > source, IntValuedEnum<GOutputStreamSpliceFlags > flags, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(source), (int)flags.value(), Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long source, int flags, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:48</i> */
	public static abstract class gboolean_callback extends Callback<gboolean_callback > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:49</i> */
	public static abstract class gboolean_callback2 extends Callback<gboolean_callback2 > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(cancellable), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:50</i> */
	public static abstract class write_async_callback extends Callback<write_async_callback > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<? > buffer, @CLong long count, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(buffer), count, io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, @Ptr long buffer, @CLong long count, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:51</i> */
	public static abstract class gssize_callback3 extends Callback<gssize_callback3 > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:52</i> */
	public static abstract class splice_async_callback extends Callback<splice_async_callback > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GInputStream > source, IntValuedEnum<GOutputStreamSpliceFlags > flags, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(source), (int)flags.value(), io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, @Ptr long source, int flags, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:53</i> */
	public static abstract class gssize_callback4 extends Callback<gssize_callback4 > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:54</i> */
	public static abstract class flush_async_callback extends Callback<flush_async_callback > {
		public final void apply(Pointer<GOutputStream > stream, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:55</i> */
	public static abstract class gboolean_callback3 extends Callback<gboolean_callback3 > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:56</i> */
	public static abstract class close_async_callback extends Callback<close_async_callback > {
		public final void apply(Pointer<GOutputStream > stream, int io_priority, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(stream), io_priority, Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long stream, int io_priority, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:57</i> */
	public static abstract class gboolean_callback4 extends Callback<gboolean_callback4 > {
		public final void apply(Pointer<GOutputStream > stream, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			apply(Pointer.getPeer(stream), Pointer.getPeer(result), Pointer.getPeer(error));
		}
		public abstract void apply(@Ptr long stream, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:58</i> */
	public static abstract class _g_reserved1_callback extends Callback<_g_reserved1_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:59</i> */
	public static abstract class _g_reserved2_callback extends Callback<_g_reserved2_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:60</i> */
	public static abstract class _g_reserved3_callback extends Callback<_g_reserved3_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:61</i> */
	public static abstract class _g_reserved4_callback extends Callback<_g_reserved4_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:62</i> */
	public static abstract class _g_reserved5_callback extends Callback<_g_reserved5_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:63</i> */
	public static abstract class _g_reserved6_callback extends Callback<_g_reserved6_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:64</i> */
	public static abstract class _g_reserved7_callback extends Callback<_g_reserved7_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/goutputstream.h:65</i> */
	public static abstract class _g_reserved8_callback extends Callback<_g_reserved8_callback > {
		public abstract void apply();
	};
}
