package gio;
import gio.GIOLibrary.GAsyncReadyCallback;
import gio.GIOLibrary.GAsyncResult;
import gio.GIOLibrary.GResolverRecordType;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : glib-2.0/gio/gresolver.h:44</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GResolverClass extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/**
	 * Signals<br>
	 * C type : reload_callback*
	 */
	@Field(1) 
	public Pointer<GResolverClass.reload_callback > reload() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * Signals<br>
	 * C type : reload_callback*
	 */
	@Field(1) 
	public GResolverClass reload(Pointer<GResolverClass.reload_callback > reload) {
		this.io.setPointerField(this, 1, reload);
		return this;
	}
	/**
	 * Virtual methods<br>
	 * C type : lookup_by_name_callback*
	 */
	@Field(2) 
	public Pointer<GResolverClass.lookup_by_name_callback > lookup_by_name() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * Virtual methods<br>
	 * C type : lookup_by_name_callback*
	 */
	@Field(2) 
	public GResolverClass lookup_by_name(Pointer<GResolverClass.lookup_by_name_callback > lookup_by_name) {
		this.io.setPointerField(this, 2, lookup_by_name);
		return this;
	}
	/** C type : lookup_by_name_async_callback* */
	@Field(3) 
	public Pointer<GResolverClass.lookup_by_name_async_callback > lookup_by_name_async() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : lookup_by_name_async_callback* */
	@Field(3) 
	public GResolverClass lookup_by_name_async(Pointer<GResolverClass.lookup_by_name_async_callback > lookup_by_name_async) {
		this.io.setPointerField(this, 3, lookup_by_name_async);
		return this;
	}
	/** C type : lookup_by_name_finish_callback* */
	@Field(4) 
	public Pointer<GResolverClass.lookup_by_name_finish_callback > lookup_by_name_finish() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : lookup_by_name_finish_callback* */
	@Field(4) 
	public GResolverClass lookup_by_name_finish(Pointer<GResolverClass.lookup_by_name_finish_callback > lookup_by_name_finish) {
		this.io.setPointerField(this, 4, lookup_by_name_finish);
		return this;
	}
	/** C type : lookup_by_address_callback* */
	@Field(5) 
	public Pointer<GResolverClass.lookup_by_address_callback > lookup_by_address() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : lookup_by_address_callback* */
	@Field(5) 
	public GResolverClass lookup_by_address(Pointer<GResolverClass.lookup_by_address_callback > lookup_by_address) {
		this.io.setPointerField(this, 5, lookup_by_address);
		return this;
	}
	/** C type : lookup_by_address_async_callback* */
	@Field(6) 
	public Pointer<GResolverClass.lookup_by_address_async_callback > lookup_by_address_async() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : lookup_by_address_async_callback* */
	@Field(6) 
	public GResolverClass lookup_by_address_async(Pointer<GResolverClass.lookup_by_address_async_callback > lookup_by_address_async) {
		this.io.setPointerField(this, 6, lookup_by_address_async);
		return this;
	}
	/** C type : lookup_by_address_finish_callback* */
	@Field(7) 
	public Pointer<GResolverClass.lookup_by_address_finish_callback > lookup_by_address_finish() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : lookup_by_address_finish_callback* */
	@Field(7) 
	public GResolverClass lookup_by_address_finish(Pointer<GResolverClass.lookup_by_address_finish_callback > lookup_by_address_finish) {
		this.io.setPointerField(this, 7, lookup_by_address_finish);
		return this;
	}
	/** C type : lookup_service_callback* */
	@Field(8) 
	public Pointer<GResolverClass.lookup_service_callback > lookup_service() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : lookup_service_callback* */
	@Field(8) 
	public GResolverClass lookup_service(Pointer<GResolverClass.lookup_service_callback > lookup_service) {
		this.io.setPointerField(this, 8, lookup_service);
		return this;
	}
	/** C type : lookup_service_async_callback* */
	@Field(9) 
	public Pointer<GResolverClass.lookup_service_async_callback > lookup_service_async() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : lookup_service_async_callback* */
	@Field(9) 
	public GResolverClass lookup_service_async(Pointer<GResolverClass.lookup_service_async_callback > lookup_service_async) {
		this.io.setPointerField(this, 9, lookup_service_async);
		return this;
	}
	/** C type : lookup_service_finish_callback* */
	@Field(10) 
	public Pointer<GResolverClass.lookup_service_finish_callback > lookup_service_finish() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : lookup_service_finish_callback* */
	@Field(10) 
	public GResolverClass lookup_service_finish(Pointer<GResolverClass.lookup_service_finish_callback > lookup_service_finish) {
		this.io.setPointerField(this, 10, lookup_service_finish);
		return this;
	}
	/** C type : lookup_records_callback* */
	@Field(11) 
	public Pointer<GResolverClass.lookup_records_callback > lookup_records() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : lookup_records_callback* */
	@Field(11) 
	public GResolverClass lookup_records(Pointer<GResolverClass.lookup_records_callback > lookup_records) {
		this.io.setPointerField(this, 11, lookup_records);
		return this;
	}
	/** C type : lookup_records_async_callback* */
	@Field(12) 
	public Pointer<GResolverClass.lookup_records_async_callback > lookup_records_async() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : lookup_records_async_callback* */
	@Field(12) 
	public GResolverClass lookup_records_async(Pointer<GResolverClass.lookup_records_async_callback > lookup_records_async) {
		this.io.setPointerField(this, 12, lookup_records_async);
		return this;
	}
	/** C type : lookup_records_finish_callback* */
	@Field(13) 
	public Pointer<GResolverClass.lookup_records_finish_callback > lookup_records_finish() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : lookup_records_finish_callback* */
	@Field(13) 
	public GResolverClass lookup_records_finish(Pointer<GResolverClass.lookup_records_finish_callback > lookup_records_finish) {
		this.io.setPointerField(this, 13, lookup_records_finish);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved4_callback*
	 */
	@Field(14) 
	public Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4() {
		return this.io.getPointerField(this, 14);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved4_callback*
	 */
	@Field(14) 
	public GResolverClass _g_reserved4(Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4) {
		this.io.setPointerField(this, 14, _g_reserved4);
		return this;
	}
	/** C type : _g_reserved5_callback* */
	@Field(15) 
	public Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : _g_reserved5_callback* */
	@Field(15) 
	public GResolverClass _g_reserved5(Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5) {
		this.io.setPointerField(this, 15, _g_reserved5);
		return this;
	}
	/** C type : _g_reserved6_callback* */
	@Field(16) 
	public Pointer<gio.GVfsClass._g_reserved6_callback > _g_reserved6() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : _g_reserved6_callback* */
	@Field(16) 
	public GResolverClass _g_reserved6(Pointer<gio.GVfsClass._g_reserved6_callback > _g_reserved6) {
		this.io.setPointerField(this, 16, _g_reserved6);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/gresolver.h:28</i> */
	public static abstract class reload_callback extends Callback<reload_callback > {
		public final void apply(Pointer<GResolver > resolver) {
			apply(Pointer.getPeer(resolver));
		}
		public abstract void apply(@Ptr long resolver);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:29</i> */
	public static abstract class lookup_by_name_callback extends Callback<lookup_by_name_callback > {
		public final Pointer apply(Pointer<GResolver > resolver, Pointer<Byte > hostname, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(hostname), Pointer.getPeer(cancellable), Pointer.getPeer(error)));
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long hostname, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:30</i> */
	public static abstract class lookup_by_name_async_callback extends Callback<lookup_by_name_async_callback > {
		public final void apply(Pointer<GResolver > resolver, Pointer<Byte > hostname, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(resolver), Pointer.getPeer(hostname), Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long resolver, @Ptr long hostname, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:31</i> */
	public static abstract class lookup_by_name_finish_callback extends Callback<lookup_by_name_finish_callback > {
		public final Pointer apply(Pointer<GResolver > resolver, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(result), Pointer.getPeer(error)));
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:32</i> */
	public static abstract class lookup_by_address_callback extends Callback<lookup_by_address_callback > {
		public final Pointer<Byte > apply(Pointer<GResolver > resolver, Pointer<GInetAddress > address, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(address), Pointer.getPeer(cancellable), Pointer.getPeer(error)), Byte.class);
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long address, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:33</i> */
	public static abstract class lookup_by_address_async_callback extends Callback<lookup_by_address_async_callback > {
		public final void apply(Pointer<GResolver > resolver, Pointer<GInetAddress > address, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(resolver), Pointer.getPeer(address), Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long resolver, @Ptr long address, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:34</i> */
	public static abstract class lookup_by_address_finish_callback extends Callback<lookup_by_address_finish_callback > {
		public final Pointer<Byte > apply(Pointer<GResolver > resolver, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(result), Pointer.getPeer(error)), Byte.class);
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:35</i> */
	public static abstract class lookup_service_callback extends Callback<lookup_service_callback > {
		public final Pointer apply(Pointer<GResolver > resolver, Pointer<Byte > rrname, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(rrname), Pointer.getPeer(cancellable), Pointer.getPeer(error)));
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long rrname, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:36</i> */
	public static abstract class lookup_service_async_callback extends Callback<lookup_service_async_callback > {
		public final void apply(Pointer<GResolver > resolver, Pointer<Byte > rrname, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(resolver), Pointer.getPeer(rrname), Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long resolver, @Ptr long rrname, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:37</i> */
	public static abstract class lookup_service_finish_callback extends Callback<lookup_service_finish_callback > {
		public final Pointer apply(Pointer<GResolver > resolver, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(result), Pointer.getPeer(error)));
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:38</i> */
	public static abstract class lookup_records_callback extends Callback<lookup_records_callback > {
		public final Pointer apply(Pointer<GResolver > resolver, Pointer<Byte > rrname, IntValuedEnum<GResolverRecordType > record_type, Pointer<GCancellable > cancellable, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(rrname), (int)record_type.value(), Pointer.getPeer(cancellable), Pointer.getPeer(error)));
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long rrname, int record_type, @Ptr long cancellable, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:39</i> */
	public static abstract class lookup_records_async_callback extends Callback<lookup_records_async_callback > {
		public final void apply(Pointer<GResolver > resolver, Pointer<Byte > rrname, IntValuedEnum<GResolverRecordType > record_type, Pointer<GCancellable > cancellable, Pointer<GAsyncReadyCallback > callback, gpointer user_data) {
			apply(Pointer.getPeer(resolver), Pointer.getPeer(rrname), (int)record_type.value(), Pointer.getPeer(cancellable), Pointer.getPeer(callback), user_data);
		}
		public abstract void apply(@Ptr long resolver, @Ptr long rrname, int record_type, @Ptr long cancellable, @Ptr long callback, gpointer user_data);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:40</i> */
	public static abstract class lookup_records_finish_callback extends Callback<lookup_records_finish_callback > {
		public final Pointer apply(Pointer<GResolver > resolver, Pointer<GAsyncResult > result, Pointer<Pointer > error) {
			return Pointer.pointerToAddress(apply(Pointer.getPeer(resolver), Pointer.getPeer(result), Pointer.getPeer(error)));
		}
		@Ptr 
		public abstract long apply(@Ptr long resolver, @Ptr long result, @Ptr long error);
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:41</i> */
	public static abstract class _g_reserved4_callback extends Callback<_g_reserved4_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:42</i> */
	public static abstract class _g_reserved5_callback extends Callback<_g_reserved5_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gresolver.h:43</i> */
	public static abstract class _g_reserved6_callback extends Callback<_g_reserved6_callback > {
		public abstract void apply();
	};
}
