package gio;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:27</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GSocketControlMessageClass extends CPPObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GObjectClass (Unsupported type) */
	/** C type : get_level_callback* */
	@Field(1) 
	public Pointer<GSocketControlMessageClass.get_level_callback > get_level() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : get_level_callback* */
	@Field(1) 
	public GSocketControlMessageClass get_level(Pointer<GSocketControlMessageClass.get_level_callback > get_level) {
		this.io.setPointerField(this, 1, get_level);
		return this;
	}
	/** C type : get_type_callback* */
	@Field(2) 
	public Pointer<GSocketControlMessageClass.get_type_callback > get_type() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : get_type_callback* */
	@Field(2) 
	public GSocketControlMessageClass get_type(Pointer<GSocketControlMessageClass.get_type_callback > get_type) {
		this.io.setPointerField(this, 2, get_type);
		return this;
	}
	/** C type : serialize_callback* */
	@Field(3) 
	public Pointer<GSocketControlMessageClass.serialize_callback > serialize() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : serialize_callback* */
	@Field(3) 
	public GSocketControlMessageClass serialize(Pointer<GSocketControlMessageClass.serialize_callback > serialize) {
		this.io.setPointerField(this, 3, serialize);
		return this;
	}
	/** C type : deserialize_callback* */
	@Field(4) 
	public Pointer<GSocketControlMessageClass.deserialize_callback > deserialize() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : deserialize_callback* */
	@Field(4) 
	public GSocketControlMessageClass deserialize(Pointer<GSocketControlMessageClass.deserialize_callback > deserialize) {
		this.io.setPointerField(this, 4, deserialize);
		return this;
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(5) 
	public Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * Padding for future expansion<br>
	 * C type : _g_reserved1_callback*
	 */
	@Field(5) 
	public GSocketControlMessageClass _g_reserved1(Pointer<gio.GVfsClass._g_reserved1_callback > _g_reserved1) {
		this.io.setPointerField(this, 5, _g_reserved1);
		return this;
	}
	/** C type : _g_reserved2_callback* */
	@Field(6) 
	public Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : _g_reserved2_callback* */
	@Field(6) 
	public GSocketControlMessageClass _g_reserved2(Pointer<gio.GVfsClass._g_reserved2_callback > _g_reserved2) {
		this.io.setPointerField(this, 6, _g_reserved2);
		return this;
	}
	/** C type : _g_reserved3_callback* */
	@Field(7) 
	public Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : _g_reserved3_callback* */
	@Field(7) 
	public GSocketControlMessageClass _g_reserved3(Pointer<gio.GVfsClass._g_reserved3_callback > _g_reserved3) {
		this.io.setPointerField(this, 7, _g_reserved3);
		return this;
	}
	/** C type : _g_reserved4_callback* */
	@Field(8) 
	public Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : _g_reserved4_callback* */
	@Field(8) 
	public GSocketControlMessageClass _g_reserved4(Pointer<gio.GVfsClass._g_reserved4_callback > _g_reserved4) {
		this.io.setPointerField(this, 8, _g_reserved4);
		return this;
	}
	/** C type : _g_reserved5_callback* */
	@Field(9) 
	public Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : _g_reserved5_callback* */
	@Field(9) 
	public GSocketControlMessageClass _g_reserved5(Pointer<gio.GVfsClass._g_reserved5_callback > _g_reserved5) {
		this.io.setPointerField(this, 9, _g_reserved5);
		return this;
	}
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:17</i> */
	public static abstract class gsize_callback extends Callback<gsize_callback > {
		public final void apply(Pointer<GSocketControlMessage > message) {
			apply(Pointer.getPeer(message));
		}
		public abstract void apply(@Ptr long message);
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:18</i> */
	public static abstract class get_level_callback extends Callback<get_level_callback > {
		public final int apply(Pointer<GSocketControlMessage > message) {
			return apply(Pointer.getPeer(message));
		}
		public abstract int apply(@Ptr long message);
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:19</i> */
	public static abstract class get_type_callback extends Callback<get_type_callback > {
		public final int apply(Pointer<GSocketControlMessage > message) {
			return apply(Pointer.getPeer(message));
		}
		public abstract int apply(@Ptr long message);
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:20</i> */
	public static abstract class serialize_callback extends Callback<serialize_callback > {
		public final void apply(Pointer<GSocketControlMessage > message, gpointer data) {
			apply(Pointer.getPeer(message), data);
		}
		public abstract void apply(@Ptr long message, gpointer data);
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:21</i> */
	public static abstract class deserialize_callback extends Callback<deserialize_callback > {
		public final Pointer<GSocketControlMessage > apply(int level, int type, @CLong long size, gpointer data) {
			return Pointer.pointerToAddress(apply$2(level, type, size, data), GSocketControlMessage.class);
		}
		@Ptr 
		public abstract long apply$2(int level, int type, @CLong long size, gpointer data);
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:22</i> */
	public static abstract class _g_reserved1_callback extends Callback<_g_reserved1_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:23</i> */
	public static abstract class _g_reserved2_callback extends Callback<_g_reserved2_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:24</i> */
	public static abstract class _g_reserved3_callback extends Callback<_g_reserved3_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:25</i> */
	public static abstract class _g_reserved4_callback extends Callback<_g_reserved4_callback > {
		public abstract void apply();
	};
	/** <i>native declaration : glib-2.0/gio/gsocketcontrolmessage.h:26</i> */
	public static abstract class _g_reserved5_callback extends Callback<_g_reserved5_callback > {
		public abstract void apply();
	};
}
