package gio;
import gio.GIOLibrary.gpointer;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * GTlsFileDatabaseInterface:<br>
 * @g_iface: The parent interface.<br>
 * * Provides an interface for #GTlsFileDatabase implementations.<br>
 * <i>native declaration : glib-2.0/gio/gtlsfiledatabase.h:11</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("GIO") 
public abstract class GTlsFileDatabaseInterface extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : GTypeInterface (Unsupported type) */
	/**
	 * Padding for future expansion<br>
	 * C type : gpointer[8]
	 */
	@Array({8}) 
	@Field(1) 
	public Pointer<gpointer > padding() {
		return this.io.getPointerField(this, 1);
	}
}
