package gtk;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Library;
/**
 * <i>native declaration : glib-2.0/glib/gtestutils.h:140</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Gtk") 
public class GTestConfig extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * Failed to convert value test_initialized of type gboolean<br>
	 * C type : gboolean
	 */
	/**
	 * Failed to convert value test_quick of type gboolean<br>
	 * C type : gboolean
	 */
	/**
	 * Failed to convert value test_perf of type gboolean<br>
	 * C type : gboolean
	 */
	/**
	 * Failed to convert value test_verbose of type gboolean<br>
	 * C type : gboolean
	 */
	/**
	 * Failed to convert value test_quiet of type gboolean<br>
	 * C type : gboolean
	 */
	/**
	 * Failed to convert value test_undefined of type gboolean<br>
	 * C type : gboolean
	 */
	public GTestConfig() {
		super();
	}
	public GTestConfig(Pointer pointer) {
		super(pointer);
	}
}
